swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/UserProfileResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /accounts/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Get account transactions
      description: Get all transactions for an account
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '401':
          description: Unauthorized
        '404':
          description: Account not found

  /transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Get transaction details
      description: Get details for a specific transaction
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Transaction details retrieved
          schema:
            $ref: '#/definitions/TransactionDetails'
    put:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Update transaction
      description: Update transaction details
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      responses:
        '200':
          description: Transaction updated
        '400':
          description: Invalid data

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Login:
    properties:
      email:
        type: string
      password:
        type: string

  LoginResponse:
    type: object
    properties:
      token:
        type: string

  UserProfileResponse:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      accounts:
        type: array
        items:
          $ref: '#/definitions/Account'

  Account:
    type: object
    properties:
      id:
        type: string
      type:
        type: string
      number:
        type: string
      balance:
        type: number

  TransactionsResponse:
    type: object
    properties:
      accountId:
        type: string
      transactions:
        type: array
        items:
          $ref: '#/definitions/Transaction'

  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: number
      balance:
        type: number

  TransactionDetails:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
        format: date-time
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
      category:
        type: string
      notes:
        type: string

  TransactionUpdate:
    type: object
    properties:
      description:
        type: string
      category:
        type: string
      notes:
        type: string